package io.github.qdiaps.solitaire.domain.rules

import io.github.qdiaps.solitaire.domain.model.BoardState
import io.github.qdiaps.solitaire.domain.model.Card
import io.github.qdiaps.solitaire.domain.model.CardLocation

/**
 * Represents a single foundation promotion step generated by [AutoCompleteResolver].
 *
 * @property card The card being promoted to a foundation pile.
 * @property from The origin location of the card ([CardLocation.Tableau] or [CardLocation.Waste]).
 * @property to The target [CardLocation.Foundation] destination pile.
 * @property resultingState The new [BoardState] after applying this promotion.
 */
data class AutoCompleteMove(
    val card: Card,
    val from: CardLocation,
    val to: CardLocation.Foundation,
    val resultingState: BoardState
) {
    /** Alias for [from] to match [io.github.qdiaps.solitaire.domain.model.Move.source]. */
    val source: CardLocation get() = from

    /** Alias for [to] to match [io.github.qdiaps.solitaire.domain.model.Move.destination]. */
    val destination: CardLocation.Foundation get() = to
}

/**
 * Pure domain resolver for Klondike Solitaire Auto-Complete mechanics.
 *
 * Evaluates whether the game board is in a safe, guaranteed-win auto-complete state
 * where all tableau columns contain zero face-down cards, stock is exhausted, and all
 * remaining cards can be sequentially promoted to foundations without deadlock.
 *
 * Generates sequential foundation promotion steps prioritized by rank (lowest first:
 * Aces before 2s, 2s before 3s, etc.) to ensure a clean, balanced victory cascade.
 */
object AutoCompleteResolver {

    /**
     * Checks whether the current [state] qualifies for auto-complete and can be safely cleared to victory.
     *
     * Auto-complete is available when:
     * 1. The game is not already won ([KlondikeRules.isGameWon] is `false`).
     * 2. The stock pile is empty/exhausted.
     * 3. All tableau columns contain zero face-down cards.
     * 4. All remaining cards in tableau and waste can be sequentially promoted to foundations.
     *
     * @param state The board state to evaluate.
     * @return `true` if auto-complete can safely cascade to victory, `false` otherwise.
     */
    fun isAutoCompleteReady(state: BoardState): Boolean {
        return resolveAllMoves(state).isNotEmpty()
    }

    /**
     * Convenience alias for [isAutoCompleteReady].
     */
    fun canAutoComplete(state: BoardState): Boolean = isAutoCompleteReady(state)

    /**
     * Calculates the next immediate foundation promotion move for [state], or `null` if no legal
     * foundation promotion is currently available.
     *
     * Prioritizes lowest rank first (Aces, then 2s, 3s, etc.) across Waste and Tableau columns,
     * maintaining balanced foundation progression.
     *
     * @param state Current [BoardState].
     * @return Next [AutoCompleteMove] candidate, or `null`.
     */
    fun nextMove(state: BoardState): AutoCompleteMove? {
        val candidates = mutableListOf<AutoCompleteMove>()

        // 1. Candidate from top of Waste pile
        if (state.waste.isNotEmpty()) {
            val wasteCard = state.waste.last()
            val targetFoundationIndex = KlondikeRules.findTargetFoundationIndex(state, wasteCard)
            if (targetFoundationIndex != null) {
                val newState = KlondikeRules.moveWasteToFoundation(state, targetFoundationIndex)
                candidates.add(
                    AutoCompleteMove(
                        card = wasteCard,
                        from = CardLocation.Waste,
                        to = CardLocation.Foundation(targetFoundationIndex),
                        resultingState = newState
                    )
                )
            }
        }

        // 2. Candidates from top card of each Tableau column (0..6)
        for (colIndex in state.tableau.indices) {
            val column = state.tableau[colIndex]
            if (column.isEmpty()) continue

            val topCard = column.last()
            if (!topCard.isFaceUp) continue

            val targetFoundationIndex = KlondikeRules.findTargetFoundationIndex(state, topCard)
            if (targetFoundationIndex != null) {
                val newState = KlondikeRules.moveTableauToFoundation(
                    state = state,
                    tableauIndex = colIndex,
                    foundationIndex = targetFoundationIndex,
                    autoExpose = true
                )
                candidates.add(
                    AutoCompleteMove(
                        card = topCard,
                        from = CardLocation.Tableau(colIndex, column.lastIndex),
                        to = CardLocation.Foundation(targetFoundationIndex),
                        resultingState = newState
                    )
                )
            }
        }

        return candidates.minWithOrNull(
            compareBy<AutoCompleteMove> { it.card.rank.value }
                .thenBy { move ->
                    when (val from = move.from) {
                        is CardLocation.Waste -> -1
                        is CardLocation.Tableau -> from.columnIndex
                        else -> 99
                    }
                }
                .thenBy { it.card.suit.ordinal }
        )
    }

    /**
     * Resolves the full sequential list of foundation promotion steps required to reach victory from [state].
     *
     * If [state] does not meet auto-complete readiness conditions or gets deadlocked during simulation,
     * returns an empty list.
     *
     * @param state Initial [BoardState].
     * @return List of sequential [AutoCompleteMove] steps leading to game victory, or empty list if unachievable.
     */
    fun resolveAllMoves(state: BoardState): List<AutoCompleteMove> {
        if (KlondikeRules.isGameWon(state)) return emptyList()
        if (state.stock.isNotEmpty()) return emptyList()
        if (state.tableau.any { column -> column.any { !it.isFaceUp } }) return emptyList()
        if (state.tableau.all { it.isEmpty() } && state.waste.isEmpty()) return emptyList()

        val moves = mutableListOf<AutoCompleteMove>()
        var current = state
        while (current.tableau.any { it.isNotEmpty() } || current.waste.isNotEmpty()) {
            val move = nextMove(current) ?: return emptyList()
            moves.add(move)
            current = move.resultingState
        }
        return moves
    }
}
