package io.github.qdiaps.solitaire.domain.rules

import io.github.qdiaps.solitaire.domain.model.BoardState
import io.github.qdiaps.solitaire.domain.model.Card
import io.github.qdiaps.solitaire.domain.model.CardLocation

/**
 * Represents a single foundation promotion step generated by [AutoCompleteResolver].
 *
 * @property card The card being promoted to a foundation pile.
 * @property from The origin location of the card ([CardLocation.Tableau], [CardLocation.Waste], or [CardLocation.Stock]).
 * @property to The target [CardLocation.Foundation] destination pile.
 * @property resultingState The new [BoardState] after applying this promotion.
 */
data class AutoCompleteMove(
    val card: Card,
    val from: CardLocation,
    val to: CardLocation.Foundation,
    val resultingState: BoardState
) {
    /** Alias for [from] to match [io.github.qdiaps.solitaire.domain.model.Move.source]. */
    val source: CardLocation get() = from

    /** Alias for [to] to match [io.github.qdiaps.solitaire.domain.model.Move.destination]. */
    val destination: CardLocation.Foundation get() = to
}

/**
 * Pure domain resolver for Klondike Solitaire Auto-Complete mechanics.
 *
 * Evaluates whether the game board qualifies for auto-complete:
 * all tableau columns contain zero face-down cards, and the board has not already won.
 *
 * Generates sequential foundation promotion steps prioritized by rank (lowest first:
 * Aces before 2s, 2s before 3s, etc.) across Tableau, Waste, and Stock piles to ensure
 * a clean, balanced victory cascade.
 */
object AutoCompleteResolver {

    /**
     * Checks whether the current [state] qualifies for auto-complete.
     *
     * Auto-complete is available when:
     * 1. The game is not already won ([KlondikeRules.isGameWon] is `false`).
     * 2. All tableau cards currently on the board are face-up (zero face-down cards).
     * 3. At least one card remains outside foundations in tableau, waste, or stock.
     *
     * @param state The board state to evaluate.
     * @return `true` if all tableau cards are face up and can auto-complete to victory, `false` otherwise.
     */
    fun isAutoCompleteReady(state: BoardState): Boolean {
        if (KlondikeRules.isGameWon(state)) return false
        val allTableauFaceUp = state.tableau.all { column -> column.all { it.isFaceUp } }
        if (!allTableauFaceUp) return false
        return state.tableau.any { it.isNotEmpty() } || state.waste.isNotEmpty() || state.stock.isNotEmpty()
    }

    /**
     * Convenience alias for [isAutoCompleteReady].
     */
    fun canAutoComplete(state: BoardState): Boolean = isAutoCompleteReady(state)

    /**
     * Calculates the next immediate foundation promotion move for [state], or `null` if no legal
     * foundation promotion is currently available.
     *
     * Prioritizes lowest rank first (Aces, then 2s, 3s, etc.) across Tableau, Waste, and Stock piles,
     * maintaining balanced foundation progression.
     *
     * @param state Current [BoardState].
     * @return Next [AutoCompleteMove] candidate, or `null`.
     */
    fun nextMove(state: BoardState): AutoCompleteMove? {
        val candidates = mutableListOf<AutoCompleteMove>()

        // 1. Candidates from top card of each Tableau column (0..6)
        for (colIndex in state.tableau.indices) {
            val column = state.tableau[colIndex]
            if (column.isEmpty()) continue

            val topCard = column.last()
            if (!topCard.isFaceUp) continue

            val targetFoundationIndex = KlondikeRules.findTargetFoundationIndex(state, topCard)
            if (targetFoundationIndex != null) {
                val newState = KlondikeRules.moveTableauToFoundation(
                    state = state,
                    tableauIndex = colIndex,
                    foundationIndex = targetFoundationIndex,
                    autoExpose = true
                )
                candidates.add(
                    AutoCompleteMove(
                        card = topCard,
                        from = CardLocation.Tableau(colIndex, column.lastIndex),
                        to = CardLocation.Foundation(targetFoundationIndex),
                        resultingState = newState
                    )
                )
            }
        }

        // 2. Candidate from top of Waste pile
        if (state.waste.isNotEmpty()) {
            val wasteCard = state.waste.last()
            val targetFoundationIndex = KlondikeRules.findTargetFoundationIndex(state, wasteCard)
            if (targetFoundationIndex != null) {
                val newState = KlondikeRules.moveWasteToFoundation(state, targetFoundationIndex)
                candidates.add(
                    AutoCompleteMove(
                        card = wasteCard,
                        from = CardLocation.Waste,
                        to = CardLocation.Foundation(targetFoundationIndex),
                        resultingState = newState
                    )
                )
            }
        }

        // 3. Candidates from any remaining card in Waste pile
        if (candidates.isEmpty() && state.waste.isNotEmpty()) {
            for (wasteIndex in state.waste.indices.reversed()) {
                val wasteCard = state.waste[wasteIndex]
                val targetFoundationIndex = KlondikeRules.findTargetFoundationIndex(state, wasteCard)
                if (targetFoundationIndex != null) {
                    val newWaste = state.waste.toMutableList().apply { removeAt(wasteIndex) }
                    val newFoundations = state.foundations.toMutableList()
                    val targetCol = newFoundations[targetFoundationIndex].toMutableList()
                    targetCol.add(wasteCard.copy(isFaceUp = true))
                    newFoundations[targetFoundationIndex] = targetCol
                    val newState = state.copy(
                        waste = newWaste,
                        foundations = newFoundations,
                        score = state.score + KlondikeRules.SCORE_WASTE_TO_FOUNDATION,
                        movesCount = state.movesCount + 1
                    )
                    candidates.add(
                        AutoCompleteMove(
                            card = wasteCard,
                            from = CardLocation.Waste,
                            to = CardLocation.Foundation(targetFoundationIndex),
                            resultingState = newState
                        )
                    )
                    break
                }
            }
        }

        // 4. Candidate from Stock pile
        if (state.stock.isNotEmpty()) {
            for (stockIndex in state.stock.indices.reversed()) {
                val stockCard = state.stock[stockIndex]
                val targetFoundationIndex = KlondikeRules.findTargetFoundationIndex(state, stockCard)
                if (targetFoundationIndex != null) {
                    val newStock = state.stock.toMutableList().apply { removeAt(stockIndex) }
                    val newFoundations = state.foundations.toMutableList()
                    val targetCol = newFoundations[targetFoundationIndex].toMutableList()
                    targetCol.add(stockCard.copy(isFaceUp = true))
                    newFoundations[targetFoundationIndex] = targetCol
                    val newState = state.copy(
                        stock = newStock,
                        foundations = newFoundations,
                        score = state.score + KlondikeRules.SCORE_WASTE_TO_FOUNDATION,
                        movesCount = state.movesCount + 1
                    )
                    candidates.add(
                        AutoCompleteMove(
                            card = stockCard,
                            from = CardLocation.Stock,
                            to = CardLocation.Foundation(targetFoundationIndex),
                            resultingState = newState
                        )
                    )
                    break
                }
            }
        }

        return candidates.minWithOrNull(
            compareBy<AutoCompleteMove> { it.card.rank.value }
                .thenBy { move ->
                    when (val from = move.from) {
                        is CardLocation.Tableau -> from.columnIndex
                        is CardLocation.Waste -> 10
                        is CardLocation.Stock -> 20
                        else -> 99
                    }
                }
                .thenBy { it.card.suit.ordinal }
        )
    }

    /**
     * Resolves the full sequential list of foundation promotion steps required to reach victory from [state].
     *
     * If [state] does not meet auto-complete readiness conditions or gets deadlocked during simulation,
     * returns an empty list.
     *
     * @param state Initial [BoardState].
     * @return List of sequential [AutoCompleteMove] steps leading to game victory, or empty list if unachievable.
     */
    fun resolveAllMoves(state: BoardState): List<AutoCompleteMove> {
        if (KlondikeRules.isGameWon(state)) return emptyList()
        if (state.tableau.any { column -> column.any { !it.isFaceUp } }) return emptyList()
        if (state.tableau.all { it.isEmpty() } && state.waste.isEmpty() && state.stock.isEmpty()) return emptyList()

        val moves = mutableListOf<AutoCompleteMove>()
        var current = state
        while (current.tableau.any { it.isNotEmpty() } || current.waste.isNotEmpty() || current.stock.isNotEmpty()) {
            val move = nextMove(current) ?: return emptyList()
            moves.add(move)
            current = move.resultingState
        }
        return moves
    }
}
