package io.github.qdiaps.solitaire.domain.solver

import io.github.qdiaps.solitaire.domain.model.BoardState
import io.github.qdiaps.solitaire.domain.model.CardLocation
import io.github.qdiaps.solitaire.domain.model.Move
import io.github.qdiaps.solitaire.domain.model.Rank
import io.github.qdiaps.solitaire.domain.rules.DrawMode
import io.github.qdiaps.solitaire.domain.rules.KlondikeRules

/**
 * Represents a single transition generated by [SolverMoveGenerator].
 *
 * @property move The domain [Move] describing the transition.
 * @property state The resulting immutable [BoardState] after applying the move.
 */
data class SolverTransition(
    val move: Move,
    val state: BoardState
)

/**
 * Enumerator of valid, non-redundant successor moves for search-based solvers.
 *
 * Implements pruning heuristics to prevent combinatorial branch explosion:
 * 1. **Terminal Pruning:** Returns no successors if the game is already won.
 * 2. **Empty Column Symmetry Pruning:** When placing a King or King-stack onto an empty tableau
 *    column, only the first empty column is considered. Targeting subsequent empty columns is
 *    mathematically symmetric and redundant.
 * 3. **Useless Lateral King Move Pruning:** A King already residing at the base of a tableau column
 *    (`cardIndex == 0`) with no face-down cards underneath is forbidden from shifting to another
 *    empty column.
 * 4. **Equivalent Parent Color Pruning:** Moving a sub-stack from one column to another whose top
 *    card has identical rank and color to the card directly above the sub-stack is pruned, as it
 *    uncovers nothing and produces a symmetric board configuration.
 * 5. **Foundation Target Uniqueness:** Foundation moves automatically resolve to the canonical
 *    foundation pile for that card's suit.
 */
object SolverMoveGenerator {

    /**
     * Generates all non-redundant [SolverTransition] items available from [state].
     *
     * @param state Current board state.
     * @param drawMode The draw rule ([DrawMode.DRAW_ONE] or [DrawMode.DRAW_THREE]).
     * @param includeFoundationToTableau Whether to generate demotions from Foundation to Tableau. Default `false`.
     * @return List of valid successor transitions.
     */
    fun generateTransitions(
        state: BoardState,
        drawMode: DrawMode = DrawMode.DRAW_ONE,
        includeFoundationToTableau: Boolean = false
    ): List<SolverTransition> {
        if (KlondikeRules.isGameWon(state)) {
            return emptyList()
        }

        val transitions = mutableListOf<SolverTransition>()
        val firstEmptyColIndex = state.tableau.indexOfFirst { it.isEmpty() }

        // 1. Tableau to Foundation promotions
        for (colIndex in state.tableau.indices) {
            val column = state.tableau[colIndex]
            if (column.isEmpty()) continue
            val topCard = column.last()
            if (!topCard.isFaceUp) continue

            val targetFoundation = KlondikeRules.findTargetFoundationIndex(state, topCard)
            if (targetFoundation != null) {
                val newState = KlondikeRules.moveTableauToFoundation(
                    state = state,
                    tableauIndex = colIndex,
                    foundationIndex = targetFoundation,
                    autoExpose = true
                )
                val uncoveredHidden = column.size >= 2 && !column[column.size - 2].isFaceUp
                val scoreDelta = KlondikeRules.SCORE_TABLEAU_TO_FOUNDATION +
                    (if (uncoveredHidden) KlondikeRules.SCORE_TURNOVER_TABLEAU_CARD else 0)

                transitions.add(
                    SolverTransition(
                        move = Move(
                            source = CardLocation.Tableau(colIndex, column.lastIndex),
                            destination = CardLocation.Foundation(targetFoundation),
                            cards = listOf(topCard),
                            scoreDelta = scoreDelta
                        ),
                        state = newState
                    )
                )
            }
        }

        // 2. Waste to Foundation promotions
        if (state.waste.isNotEmpty()) {
            val wasteCard = state.waste.last()
            val targetFoundation = KlondikeRules.findTargetFoundationIndex(state, wasteCard)
            if (targetFoundation != null) {
                val newState = KlondikeRules.moveWasteToFoundation(state, targetFoundation)
                transitions.add(
                    SolverTransition(
                        move = Move(
                            source = CardLocation.Waste,
                            destination = CardLocation.Foundation(targetFoundation),
                            cards = listOf(wasteCard),
                            scoreDelta = KlondikeRules.SCORE_WASTE_TO_FOUNDATION
                        ),
                        state = newState
                    )
                )
            }
        }

        // 3. Tableau to Tableau sequence moves
        for (fromCol in state.tableau.indices) {
            val sourceCol = state.tableau[fromCol]
            if (sourceCol.isEmpty()) continue

            for (cardIndex in sourceCol.indices) {
                val baseCard = sourceCol[cardIndex]
                if (!baseCard.isFaceUp) continue

                val movingStack = sourceCol.subList(cardIndex, sourceCol.size)
                if (!KlondikeRules.isValidTableauSequence(movingStack)) continue

                for (toCol in state.tableau.indices) {
                    if (toCol == fromCol) continue
                    val targetCol = state.tableau[toCol]

                    if (targetCol.isEmpty()) {
                        // Pruning Rule: Non-King cannot move to empty column
                        if (baseCard.rank != Rank.KING) continue
                        // Pruning Rule: King at base of column moving to another empty column is useless lateral move
                        if (cardIndex == 0) continue
                        // Pruning Rule: Only target the first empty column
                        if (toCol != firstEmptyColIndex) continue
                    } else {
                        // Pruning Rule: Moving sub-stack to equivalent parent rank and color is symmetric
                        if (cardIndex > 0 && sourceCol[cardIndex - 1].isFaceUp) {
                            val parentCard = sourceCol[cardIndex - 1]
                            val targetTop = targetCol.last()
                            if (parentCard.rank == targetTop.rank && parentCard.suit.isRed == targetTop.suit.isRed) {
                                continue
                            }
                        }
                    }

                    if (KlondikeRules.canMoveTableauToTableau(state, fromCol, cardIndex, toCol)) {
                        val newState = KlondikeRules.moveTableauToTableau(
                            state = state,
                            fromColumnIndex = fromCol,
                            cardIndex = cardIndex,
                            toColumnIndex = toCol,
                            autoExpose = true
                        )
                        val uncoveredHidden = cardIndex > 0 && !sourceCol[cardIndex - 1].isFaceUp
                        val scoreDelta = if (uncoveredHidden) KlondikeRules.SCORE_TURNOVER_TABLEAU_CARD else 0

                        transitions.add(
                            SolverTransition(
                                move = Move(
                                    source = CardLocation.Tableau(fromCol, cardIndex),
                                    destination = CardLocation.Tableau(toCol, targetCol.size),
                                    cards = movingStack,
                                    scoreDelta = scoreDelta
                                ),
                                state = newState
                            )
                        )
                    }
                }
            }
        }

        // 4. Waste to Tableau placements
        if (state.waste.isNotEmpty()) {
            val wasteCard = state.waste.last()
            for (toCol in state.tableau.indices) {
                val targetCol = state.tableau[toCol]
                if (targetCol.isEmpty() && toCol != firstEmptyColIndex) {
                    continue
                }

                if (KlondikeRules.canMoveWasteToTableau(state, toCol)) {
                    val newState = KlondikeRules.moveWasteToTableau(state, toCol)
                    transitions.add(
                        SolverTransition(
                            move = Move(
                                source = CardLocation.Waste,
                                destination = CardLocation.Tableau(toCol, targetCol.size),
                                cards = listOf(wasteCard),
                                scoreDelta = KlondikeRules.SCORE_WASTE_TO_TABLEAU
                            ),
                            state = newState
                        )
                    )
                }
            }
        }

        // 5. Foundation demotions to Tableau (optional)
        if (includeFoundationToTableau) {
            for (foundationIndex in state.foundations.indices) {
                val pile = state.foundations[foundationIndex]
                if (pile.isEmpty()) continue
                val foundationCard = pile.last()

                for (toCol in state.tableau.indices) {
                    val targetCol = state.tableau[toCol]
                    if (targetCol.isEmpty() && toCol != firstEmptyColIndex) {
                        continue
                    }

                    if (KlondikeRules.canMoveFoundationToTableau(state, foundationIndex, toCol)) {
                        val newState = KlondikeRules.moveFoundationToTableau(state, foundationIndex, toCol)
                        transitions.add(
                            SolverTransition(
                                move = Move(
                                    source = CardLocation.Foundation(foundationIndex),
                                    destination = CardLocation.Tableau(toCol, targetCol.size),
                                    cards = listOf(foundationCard),
                                    scoreDelta = KlondikeRules.SCORE_FOUNDATION_TO_TABLEAU
                                ),
                                state = newState
                            )
                        )
                    }
                }
            }
        }

        // 6. Stock Draw or Recycle
        if (KlondikeRules.canDraw(state)) {
            val newState = KlondikeRules.draw(state, drawMode)
            val drawCount = minOf(if (drawMode == DrawMode.DRAW_ONE) 1 else 3, state.stock.size)
            val drawnCards = state.stock.take(drawCount).map { it.copy(isFaceUp = true) }

            transitions.add(
                SolverTransition(
                    move = Move(
                        source = CardLocation.Stock,
                        destination = CardLocation.Waste,
                        cards = drawnCards,
                        scoreDelta = 0
                    ),
                    state = newState
                )
            )
        } else if (KlondikeRules.canRecycle(state)) {
            val newState = KlondikeRules.recycle(state)
            val recycledCards = state.waste.map { it.copy(isFaceUp = false) }

            transitions.add(
                SolverTransition(
                    move = Move(
                        source = CardLocation.Waste,
                        destination = CardLocation.Stock,
                        cards = recycledCards,
                        scoreDelta = 0
                    ),
                    state = newState
                )
            )
        }

        return transitions
    }

    /**
     * Convenience method returning only the successor [BoardState]s from [generateTransitions].
     */
    fun generateSuccessorStates(
        state: BoardState,
        drawMode: DrawMode = DrawMode.DRAW_ONE,
        includeFoundationToTableau: Boolean = false
    ): List<BoardState> = generateTransitions(state, drawMode, includeFoundationToTableau).map { it.state }
}
